// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  indent = 14,
  dedent = 15,
  newline = 16,
  Program = 1,
  Process = 2,
  Assignment = 3,
  Name = 4,
  Integer = 5,
  Input = 6,
  Channel = 7,
  Output = 8,
  Skip = 9,
  Stop = 10,
  Sequence = 11,
  Seq = 12
