// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  indent = 15,
  dedent = 16,
  newline = 17,
  eof = 18,
  Comment = 1,
  Program = 2,
  Process = 3,
  Assignment = 4,
  Name = 5,
  Integer = 6,
  Input = 7,
  Channel = 8,
  Output = 9,
  Skip = 10,
  Stop = 11,
  Sequence = 12,
  Parallel = 13
