// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {indentation, newlines, trackIndent} from "./tokens.js"
const spec_Name = {__proto__:null,"~":48, BITNOT:48, NOT:48, SIZE:48, "+":50, "*":50, "/":50, "\\":50, REM:50, PLUS:50, TIMES:50, "/\\":50, "\\/":50, "><":50, BITAND:50, BITOR:50, AND:50, OR:50, "=":50, "<>":50, "<":50, ">":50, ">=":50, "<=":50, AFTER:50, "-":52, MINUS:52, SKIP:58, STOP:60, SEQ:62, PAR:66}
export const parser = LRParser.deserialize({
  version: 14,
  states: "%WOYQSOOOkQSO'#CdOOQR'#Cf'#CfOOQR'#Cg'#CgOvQUO'#ChO{QUO'#CiOOQR'#C_'#C_QOQSOOO!QQSO'#CeO!YQSO,58zO!hQTO,59SO!mQTO,59TO!YQSO,59PO!rQSO,58}O!wQVO'#CrO#]QSO'#CrOOQR'#Cs'#CsOOQR1G.f1G.fOYQSO1G.nOYQSO1G.oOOQR1G.k1G.kOOQR1G.i1G.iO#]QSO,59^OOQR,59^,59^O#eQVO'#C|O#pQVO7+$YO#xQVO7+$ZOOQR1G.x1G.xOYQSO,59hOOQR<<Gt<<GtOOQR<<Gu<<GuOOQR1G/S1G/S",
  stateData: "$Q~OdOSPOS~OTPOmQOnROoSOqTO~OeXOkWXlWX~OaYO~OaZO~Ok]Ol[O~OT`OU`Oh_Oj_O~O_bO~O_cO~OTeO~OifOjgO^fX`fXafXbfX~OT`OU`O~OalO`pXbpX~O`mObmO~O`nObnO~O",
  goto: "!qqPPPrzPPz!QzzzzzPPPPPPPP!W!^PPPPPPPP!hQVOVhbclXUObclXWObclQaXRd[S^X[Qg_RkfQibQjcRol",
  nodeNames: "⚠ Comment Program Process Assignment Name Integer Input Channel Output Skip Stop Sequence Parallel",
  maxTerm: 33,
  context: trackIndent,
  skippedNodes: [0,1],
  repeatNodeCount: 0,
  tokenData: "$W~RaX^!Wpq!Wqr!{!P!Q#Q!Q![#c![!]#k!a!b#v!c!}#{#T#o#{#y#z!W$f$g!W#BY#BZ!W$IS$I_!W$I|$JO!W$JT$JU!W$KV$KW!W&FU&FV!W~!]Yd~X^!Wpq!W#y#z!W$f$g!W#BY#BZ!W$IS$I_!W$I|$JO!W$JT$JU!W$KV$KW!W&FU&FV!W~#QOl~~#TP!P!Q#W~#]QP~OY#WZ~#W~#hPU~!Q![#c~#nP!_!`#q~#vOe~~#{Ok~~$QQT~!c!}#{#T#o#{",
  tokenizers: [indentation, newlines, 0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 5, get: value => spec_Name[value] || -1}],
  tokenPrec: 0
})
